# ---------- Overriding hydra default configs ----------

# Dataset
data_dir: '/Users/yukaisun/Documents/Research/pytorch學習/mnist'

# Training
batch_size: 32
hidden_dim: 128
num_workers: 0
num_epochs: 20
learning_rate: 1e-3
exp_name: 'exp001'
